[package]
name = "ds210_final_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = {version="1.0.152", features=["derive"]}
rand="0.8.5"
backtrace = "0.3.62"


